# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('content', models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['-posted'],
                'verbose_name': '\u0437\u0430\u043f\u0438\u0441\u044c \u0433\u043e\u0441\u0442\u0435\u0432\u043e\u0439 \u043a\u043d\u0438\u0433\u0438',
                'verbose_name_plural': '\u0437\u0430\u043f\u0438\u0441\u0438 \u0433\u043e\u0441\u0442\u0435\u0432\u043e\u0439 \u043a\u043d\u0438\u0433\u0438',
            },
        ),
    ]
